FROM toniblyx/prowler:stable

ENV MPLBACKEND=Agg

RUN python -m pip install --no-cache-dir pandas matplotlib

COPY patches/prowler/ecs_securitygroup_restrict_ssh_internet.py /home/prowler/prowler/providers/alibabacloud/services/ecs/ecs_securitygroup_restrict_ssh_internet/ecs_securitygroup_restrict_ssh_internet.py
COPY patches/prowler/ecs_securitygroup_restrict_rdp_internet.py /home/prowler/prowler/providers/alibabacloud/services/ecs/ecs_securitygroup_restrict_rdp_internet/ecs_securitygroup_restrict_rdp_internet.py
